Paymenter/Paymenter

themes/default/views/admin/tickets/create.blade.php
themes/default/views/admin/tickets/index.blade.php

Darkmode to the Ticket Area

---

themes/default/views/admin/index.blade.php
themes/default/views/admin/tickets/show.blade.php

Updated the Darkmode:
Now the show Ticket page has full Darkmode
Made some adjusts to the Admin ticket overview since there was the bug that multiple tickets didn´t had darkmode but blended you like a flashbang in csgo at midnight

Updated Darkmode

---

themes/default/views/admin/index.blade.php

Added the Feature that you can a Ticket by clicking on it at the Admin dashboard.

Updated Design

---

themes/default/views/home.blade.php
themes/default/views/layouts/adminnavigation.blade.php
themes/default/views/layouts/navigation.blade.php

Added a Button that only shows if the User is admin and then leads the User to the Admin dashboard.
Added a Button to the Admin dashboard that redirects to the Userdashboard

Implemented change Dashboard Button

---

themes/default/views/admin/index.blade.php
themes/default/views/home.blade.php
themes/default/views/layouts/adminnavigation.blade.php
themes/default/views/layouts/navigation.blade.php

Tickets now Show the current status(replied,closed) and the User issued.
The App name has been adjusted in darkmode.

Some design updates

---

themes/default/tailwind.config.js
themes/default/views/admin/index.blade.php
themes/default/views/admin/products/create.blade.php
themes/default/views/admin/products/edit.blade.php
themes/default/views/home.blade.php
themes/default/views/tickets/index.blade.php

- Added that when you edit a product you see 1,99 instead of 15,9.
- Added Darkmode to `products/create`
- 4C

A few Adjustments

---

themes/default/views/auth/passwords/confirm.blade.php

- Added Darkmode to domain/confirm-password.
- 6F

Darkmode Update

---

themes/default/views/layouts/adminnavigation.blade.php

Shortened the openMenu function so that it takes up less space and so it opens and closes the menu as expected.

Redid the openMenu function

---

themes/default/views/admin/index.blade.php

I haven't dabbled with mktime in a while so it may not work as expected on a different month so double check that.

Simplified data and label chart arrays

---

themes/default/views/layouts/adminnavigation.blade.php
themes/default/views/layouts/navigation.blade.php

Added change password to drop-down menu

Added change password

---

app/Http/Controllers/TicketsController.php
themes/default/views/tickets/index.blade.php

Updated ticket page

---

themes/default/views/tickets/index.blade.php

I know this will probably never happen if the data is correctly stored but is a temp fix for now due to no column added.

Check for null

---

app/Http/Controllers/Admin/MigrateController.php
routes/admin.php
themes/default/views/admin/migrate/blesta.blade.php
themes/default/views/admin/migrate/index.blade.php
themes/default/views/admin/migrate/whmcs.blade.php
themes/default/views/layouts/adminnavigation.blade.php

This is still WIP so please do not change any files related to this unless your Corwin :)

Added WHMCS Migrate option

---

app/Http/Controllers/Admin/MigrateController.php
app/Http/Controllers/HomeController.php
app/Models/Invoices.php
themes/default/views/admin/migrate/whmcs.blade.php
themes/default/views/home.blade.php

Also added a 'Your Info' section just because I didn't want it to be empty. Added validation for home page.

Updated Migrate for WHMCS and validation for home page

---

themes/default/views/admin/index.blade.php
themes/default/views/home.blade.php
themes/default/views/product.blade.php
themes/default/views/welcome.blade.php

- Updated styling of dashboard
- Made dashboard mobile friendly
- Updated styling of products
**Dashboard**
**Products**

Updated styling of dashboard and products

---

themes/default/views/admin/clients/create.blade.php
themes/default/views/admin/clients/edit.blade.php
themes/default/views/layouts/sidenavigation.blade.php

Updated client view and create layout

---

app/Classes/API.php
app/Http/Controllers/API/Admin/APIController.php
app/Http/Controllers/API/Admin/InvoiceController.php
app/Http/Controllers/API/Admin/TicketController.php
app/Http/Controllers/API/Admin/UserController.php
app/Http/Controllers/Clients/APIController.php
app/Http/Kernel.php
app/Http/Middleware/AdminAPIRequest.php
app/Http/Middleware/IsAdmin.php
app/Providers/RouteServiceProvider.php
routes/API/admin_api.php
routes/API/client_api.php
themes/default/views/layouts/navigation.blade.php
themes/default/views/layouts/sidenavigation.blade.php

Added admin API

---

themes/default/views/components/footer.blade.php
themes/default/views/layouts/admin.blade.php
themes/default/views/layouts/app.blade.php

Allows for easier modification of the footer.

feat: Footer component for easier modification

---

lang/pl.json
themes/default/views/product.blade.php

upgraded out of stock information from https://github.com/Paymenter/Paymenter/pull/138

LANG, OUT OF STOCK

---

app/Console/Commands/CheckUpdates.php
app/Console/Kernel.php
config/app.php
database/seeders/SettingSeeder.php
themes/default/views/admin/clients/edit.blade.php
themes/default/views/clients/home.blade.php
themes/default/views/components/paymenter-update.blade.php
themes/default/views/layouts/admin.blade.php
themes/default/views/layouts/app.blade.php
themes/default/views/layouts/navigation.blade.php

Some UI changes, new paymenter version is available for download notify

---

themes/default/views/admin/announcements/create.blade.php
themes/default/views/admin/orders/index.blade.php

Made some UI/UX changes to the order tab and announcement create tab.
Made on version
v0.8.2 (Latest)

QoL Update in order ordening

---

app/Http/Controllers/Admin/ClientController.php

Made it so that you can no longer delete yourself to prevent issue #104  from happening.
Closes #104

Added so that you  cannot delete yourself

---

themes/default/views/clients/home.blade.php
themes/default/views/clients/tickets/index.blade.php
themes/default/views/components/success.blade.php
themes/default/views/layouts/navigation.blade.php
themes/default/views/livewire/checkout/index.blade.php

Please note that all pictures were taken before changes.
Added padding to these buttons
https://cdn.padow.ru/vfIDG
Added .00 at the Total Today for more consistancy
https://cdn.padow.ru/loNKN
Made it so it doesnt offset.
https://cdn.padow.ru/feu5q
Removed the bottem bar for a cleaner look
https://cdn.padow.ru/hzA52
'Centered' the No services found. text
https://cdn.padow.ru/F5rGa
Added padding
https://cdn.padow.ru/RxGkn
Added padding
https://cdn.padow.ru/r9vQC
Made it so that the colors represent the state of the ticket. (Open = Green, Closed = Red) https://cdn.padow.ru/ZR3YS
Changed 'Never' to 'Doesn't Expire'
https://cdn.padow.ru/yVpiu
Please note that all pictures were taken before changes.

Fixed Multiple UI imperfections. See description for more details.

---

lang/ar.json
lang/bs.json
lang/cs.json
lang/da.json
lang/de.json
lang/en.json
lang/es.json
lang/hu.json
lang/ja.json
lang/nl.json
lang/pl.json
lang/pt.json
lang/ro.json
lang/sk.json
lang/sv.json
lang/zh.json
themes/default/views/admin/emails/index.blade.php
themes/default/views/admin/settings/settings/login.blade.php
themes/default/views/auth/register.blade.php
themes/default/views/livewire/checkout/config.blade.php

Added the abillity to disable register (idk why yall want this but it was suggested.)

---

lang/da.json

Update da.json to correct translations

---

lang/da.json

Misunderstood the login translation for da.json, quick fix.

Misunderstood the login translation for da.json, quick fix.

---

app/Livewire/Admin/Orders/Index.php

Allows orders to be searchable

Order Searchable Fix

---

update.sh

This pull request goes over multiple [ShellCheck](http://shellcheck.net/) advisories and generally improves command logging by writing a function for it.

Address ShellCheck advisories and improve command logging on `update.sh`.

---

app/Livewire/Checkout/Index.php
themes/default/views/admin/coupons/edit.blade.php

Fixed issue where max uses input field was not displaying the current value.
Fixed issue where max uses was not being set correctly.

Fix max uses on coupon code

---

app/Admin/Resources/CategoryResource.php
app/Classes/helpers.php

also fixes category name getting automatically deleted when typing fast

fix: theme helper not returning default value of setting when it is set but is null

---

app/Classes/Navigation.php

Closes #526
On behalf of @Sarthak-07

chore(nav): home and dashboard navigations

---

themes/default/views/components/captcha/turnstile.blade.php

Adds widget size adjustment via API that takes up all available space (100% with a minimum of 300px), and also check the dark mode to adapt the widget theme.

feat: turnstile theme and flex size

---

app/Admin/Resources/CategoryResource.php
app/Models/Category.php
themes/default/views/products/index.blade.php

and also fixed misalignment of products

fix: category resource trying to save parent_id as array

---

app/Admin/Resources/CategoryResource.php
app/Admin/Resources/ProductResource.php
app/Admin/Resources/RoleResource.php
app/Admin/Resources/ServiceCancellationResource.php
app/Admin/Resources/ServiceResource.php
app/Admin/Resources/UserResource.php

- Fix error when creating user: "Attempt to read property 'tfa_secret' on null"
- Add validation for role name uniqueness and required field.
- Add 'required' validation for slug and allow_quantity fields in forms.
- Resolve 'currency_code' default value error and improve price input validation.
- Prevent error when accessing user email on null order or user.

fix: resolve multiple issues and add validation improvements

---

app/Admin/Resources/TicketResource.php
app/Admin/Resources/TicketResource/Pages/EditTicket.php
app/Classes/Settings.php
themes/default/views/tickets/show.blade.php

- Resolved an issue where the department was stored as an index in the admin dashboard and as a string in the user dashboard.

Fix : department indexing inconsistency between admin and user dashboards

---

app/Console/Commands/MigrateOldData.php

Batching is bypassed if the records are less than the batch size.
By default the batch size is 500, but it can be adjusted by editing the variable, in future I might make it an option in the command.

feat: add batching to almost all migrate functions and general improvements

---

app/Admin/Resources/UserResource.php
app/Admin/Resources/UserResource/Pages/ShowCredits.php
app/Models/Service.php

fix: credits not displaying properly in admin area

---

app/Console/Commands/MigrateOldData.php
extensions/Servers/Pterodactyl/Pterodactyl.php
extensions/Servers/Virtfusion/Virtfusion.php

Added the `product_settings` and `product_upgrades` migrator functions that were previously missing.
Also fixed a tiny issue occuring due to old fields having encryption but new one doesn't.

fix(migrator): migrate functions for product_settings and product_upgrades

---

extensions/Others/Affiliates/Livewire/Affiliates/Affiliate.php

Solved problem with creation of affiliates

---

extensions/Servers/Pterodactyl/Pterodactyl.php

Update the link to the documentation.
The old one is not working.

Update Pterodactyl server extension

---

themes/default/views/components/navigation/sidebar-links.blade.php

Fixes the credits item being shown while credits are disabled.

fix: Hide disabled child menu items

---

themes/default/views/dashboard.blade.php

earlier the view all button under the tickets section was linked to services, now it is linked to tickets

fix: view all tickets btn

---

extensions/Servers/Virtualizor/Virtualizor.php

I created the function for upgradeServer in order to have the upgrade function for virtualizor. it is already possible to put it in a commit.
Attention: we do not know why it does not work with the upgrade by the client but only by the admin through the trigger in his panel

Update File "Virtualizor.php" with the upgradeServer

---

extensions/Servers/Pterodactyl/Pterodactyl.php

Fixes #791
I additionally added descriptions for the most input fields.
Also changed for example swap to allow -1 (for unlimited) (0 stands for disable)

fix: validate limitations and improve form field descriptions

---

app/Admin/Pages/Settings.php
app/Classes/FilamentInput.php

https://github.com/user-attachments/assets/e3b8d003-2270-4bde-9a6d-e8d9ad086d49
sorry

feat: allow any color inputs and reset colors in settings

---

themes/default/views/components/captcha/turnstile.blade.php

Reverts Paymenter/Paymenter#849

Revert "Fix Turnstile dark mode"

---

themes/default/views/services/show.blade.php

Ability to let extensions simply define target tabs for url

feat(service-buttons): open url in new tab

---

app/Livewire/Auth/Register.php
themes/default/views/auth/register.blade.php

https://github.com/Paymenter/Paymenter/pull/912#issuecomment-3188453652
here only checkbox addets

TOS Checkbox for the Register page

---

app/Livewire/Products/Index.php
app/Livewire/Products/Show.php
app/Models/Plan.php
app/Models/Product.php
app/Models/Traits/HasPlans.php

This pull request introduces several improvements to how products and their related data are loaded and queried in the application. The most significant changes are focused on optimizing eager loading of relationships for products and plans, refining query logic for configuration options, and ensuring proper sorting and filtering. These updates should improve performance and data consistency when displaying products and their related entities.
**Eager Loading and Data Retrieval Enhancements:**
* Updated product queries in `app/Livewire/Products/Index.php` and `app/Livewire/Products/Show.php` to eagerly load related `plans.prices` and nested `configOptions.children.plans.prices` for more efficient data access and rendering. [[1]](diffhunk://#diff-f672b0302dabf0eaa218054dc0058b306ac879a24cb4 …

Enhance Product and Plan Data Loading with Eager Loading, Currency-Contextual Pricing, and Sorting
