Paymenter/Paymenter

app/Livewire/Admin/Clients/Index.php, app/Livewire/Admin/Invoices/Index.php, app/Livewire/Admin/Orders/Index.php
Changes default sort order for Invoices, Orders and Clients to be sorted by the latest ID by default.
=> Change default sort order to latest ID

database/migrations/2024_01_15_164416_update_order_products_config_key_value_type.php
This PR will fix issues that third party extensions may have when dealing with data longer than 119 characters. For example an RSA SSH-key can be more than 119 characters which will cause the extension to not function properly
=> Update order config key value types

README.md
Because 'advanced' starts with an 'a', it is 'an'.
=> docs: fix grammar mistake

update.sh
Currently there are two variables for defining the release URL for the `update.sh` script assigned the following values:
`$URL` https://github.com/paymenter/paymenter/releases/latest/download/paymenter.tar.gz
`$DEFAULT_URL` https://github.com/paymenter/paymenter/releases/latest/download/paymenter.tar.gz
When `$URL` is empty, the value of `$DEFAULT_URL` gets assigned to `$URL`, but this never happens unless made completely empty by editing the file rendering a specific "if" statement completely useless.
The changes made in this pull request will instead throw an error when `$URL` is empty, which only happens if a user would edit the file and remove the value of `$URL`. I've also colored errors red because why not.
=> Color errors red and no longer make use of the `$DEFAULT_URL` variable.

themes/default/views/admin/logs/index.blade.php
Logs page layout breaks when log text has to overflow onto multiple lines. This PR makes it so that the height of the log button fits the text correctly 🙂
=> fix: fit logs container to text within

themes/default/views/admin/invoices/show.blade.php
This pull request updates the invoice details to ensure that the paid_reference field is correctly displayed when an invoice is marked as paid. The change ensures that the payment reference is captured and shown properly in the invoice details.
=> fix: Update invoice details to display paid reference

app/Admin/Resources/InvoiceResource/Pages/EditInvoice.php, app/Livewire/Invoices/Show.php, themes/default/views/invoices/show.blade.php
Allows users to download invoices pdf and also adds invoice id in the pdf name.
=> feat: allow users to download invoices pdf

themes/default/views/components/captcha/index.blade.php, themes/default/views/components/captcha/turnstile.blade.php
With the change to dark mode on the body, it seems to have stopped working. I haven’t tested it but it should work. Also, the `items-center` is removed which was preventing full width for Turnstile.
=> Fix: Turnstile width/dark mode issues

app/Admin/Resources/TicketResource.php
This PR fixes a server-side 500 Internal Server Error that occurred when sorting tickets by customer name or filtering tickets by user in the search box.
The error was caused by a subquery attempting to select a name column from the users table, which doesn’t exist. The SQL error was:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'SELECT'`
=> fix: resolve 500 error when sorting tickets by customer name

app/Console/Commands/CronJob.php
Description:
This PR fixes the logic for automatically closing tickets with replied status after the configured time period.
What was wrong:
The original logic checked whether any message not from the ticket owner was older than the configured days. This could incorrectly close tickets just because the ticket was created a long time ago, even if the last reply was recent.
What’s changed:
Now, the script checks the timestamp of the last message, and only closes the ticket if that last message is older than the configured threshold. This ensures tickets are only closed when there’s been no reply activity for the set number of days.
=> Fix incorrect auto-closing logic for replied tickets in CronJob

extensions/Servers/Convoy/Convoy.php
I noticed that when the backups field is set to 0, it grants users an unlimited backup quota. This could lead to issues if we don’t intend to provide extra backups to users, as it might not align with our intended behavior.
=> fix: Disable Convoy backups when set to 0, not unlimited

app/Admin/Resources/InvoiceResource/Pages/CreateInvoice.php, app/Console/Commands/CronJob.php, app/Events/Invoice/Created.php, app/Events/Invoice/Creating.php, app/Events/Invoice/Finalized.php, app/Events/Invoice/Updating.php, app/Events/Order/Creating.php, app/Events/Order/Finalized.php, app/Events/Order/Updating.php, app/Listeners/SendMailListener.php, app/Livewire/Cart.php, app/Livewire/Services/Upgrade.php, app/Models/Invoice.php, app/Models/Order.php, app/Observers/InvoiceObserver.php, app/Observers/OrderObserver.php, extensions/Others/DiscordNotifications/DiscordNotifications.php
The problem was that the CreateEvent was fired before Filament inserted the related rows. I added a virtual property in the Invoice model, and added a dispatch to fire the event after Filament inserted the Item rows.
Also fixes the duplicate mail sending, as it was sent by both the event and the handleRecordCreation method (and it is better imo to keep the email sending logic in the event)
Fix #663
=> Fix duplicate invoice email and missing item lines on admin invoice creation

app/Classes/Settings.php, lang/en/invoices.php, lang/nl/invoices.php, resources/views/pdf/invoice.blade.php
Adds settings for company tax id and company (chamber of commerce) id and show them on the invoice PDF as required by most countries.
=> feat: Company tax id and company id

extensions/Gateways/Stripe/Stripe.php
Placeholder is labeled wrong. Showed by @NorteX-dev on discord 
Discord Message ID: 1366384843230810242
=> Fix: Wrong name in stripe ext. Placeholder

extensions/Servers/Convoy/Convoy.php
Fix intermittent VM creation failures by aligning the special‐character regex behavior with upstream Convoy.
https://github.com/ConvoyPanel/panel/blob/develop/resources/scripts/util/validation.ts#L26-L34
=> fix: update special-char requirement in Convoy password regex

app/Helpers/ExtensionHelper.php, app/Livewire/Invoices/Show.php
I tried implementing the canUseGateway($items, $type)-hook, but got some errors. These are my easy fixes which worked well for me, as I thought they must be typos.
The first error I got by just hooking up a (meaningless/empty) canUseGateway(), which I traced back to a typo in getCheckoutGateways().
The second error came when I recieved NULL as $items in invoices. Based on the [documentation](https://paymenter.org/development/extensions/gateway#canusegateway) I guess it should be the list of InvoiceItem.
Keep in mind I'm not a seasoned PHP-developer, and this is my first try at a pull request.
=> fix: couple of bugs when payment gateway implements canUseGateway()

themes/default/views/components/navigation/index.blade.php
prevents sidebar in the admin area from scrolling to top after clicking sidebar links for better UX
before: https://github.com/user-attachments/assets/97932641-37a9-48ff-b80b-b40e75651d6f
after: https://github.com/user-attachments/assets/67fae27f-6877-4acf-8e14-4df3ecc8dfba
=> fix: hide register btn on mobile when disabled

extensions/Servers/Pterodactyl/Pterodactyl.php
the environment variable for location didn't match the docs. this fixes the "location" config option to work as expected, along with "location_ids" to work by converting it into an array.
=> fix(ext): overwrite config option data for "location"

app/Providers/AppServiceProvider.php, app/Support/Passport/ScopeRegistry.php
This PR introduces a new `ScopeRegistry` class to centralize and dynamically manage OAuth scopes used with Laravel Passport. This replaces the previously hardcoded `Passport::tokensCan([...])` in `AppServiceProvider`.
---
* **Replaced static scope declaration**:
```php
Passport::tokensCan([
'profile' => 'View your profile',
]);
```
➜ **Now uses**:
```php
Passport::tokensCan(ScopeRegistry::getAll());
```
* **Added `ScopeRegistry` class** at `App\Support\Passport\ScopeRegistry`:
* `add(string $scope, string $description)` – register a single scope
* `addMany(array $scopes)` – register multiple scopes at once
* `getAll(): array` – returns all registered scopes
* Automatically avoids duplicate keys
* **Extensions can now register their own scopes** during `boot()`:
```php …
```
=> Refactor Passport Scope Handling with ScopeRegistry

extensions/Servers/Pterodactyl/Pterodactyl.php
Yea that's my bad. Did it the wrong way around in #793
Proof from Pterodactyl:
=> fix(ext): Wrong swap description

app/Livewire/Services/Show.php, themes/default/views/services/show.blade.php
Added custom fields to `getActions`, letting extension add more fields when needed.
For example, HestiaCP don't have SSO link, therefore simple button won't help.
The API for adding text field:
```php
public function getActions(Service $service, $settings, $properties): array
{
if (!isset($properties['hestiacp_username'])) {
return [];
}
return [
[
'type' => 'text',
'text' => $properties['hestiacp_username'],
'label' => 'HestiaCP Username',
],
[
'type' => 'text',
'text' => $properties['hestiacp_password'],
'label' => 'HestiaCP Password',
]
];
}
```
How it's look like:
Solves #939.
=> feat: text fields in getAction

app/Models/Plan.php
This commit addresses a TypeError that occurred during checkout. The billing_period field, which should be an integer, was sometimes being typed as a string.
The fix ensures that billing_period is explicitly cast to an integer before it is used to calculate the end date, preventing the TypeError and ensuring the checkout process functions correctly.
=> Cast billing_period to integer

app/Console/Commands/FetchEmails.php, routes/console.php
What:
- Explicitly disconnect IMAP mailbox after fetching emails to avoid stale sockets and EOF errors.
- Add ->withoutOverlapping() to the FetchEmails schedule to prevent concurrent executions.
Why:
These changes reduce intermittent "Server closed the connection (EOF)" errors and improve the reliability of email importing.
Files changed:
- app/Console/Commands/FetchEmails.php
- routes/console.php
=> Ensure IMAP disconnect and avoid overlapping scheduled FetchEmails runs
